
<div class="row">
    <div class="col-md-12">
        <h1>Project Details</h1>
        <hr>
    
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('application/default', array('controller' => 'project', 'action' => 'enter_detail', 'id' => $this->id)));
            $form->prepare();
            
            echo $this->form()->openTag($form);
            foreach ($form as $element) {
                echo $this->formRow($element);
            }
            echo $this->form()->closeTag();
        ?>
        
    </div>
</div>