<div class="row">
    <div class="col-md-12">
        <h1>Projects</h1>
        <a class="btn btn-sm btn-success" href="<?php echo $this->url('application/default', array(
                            'controller' => 'project',
                            'action'     => 'enter_detail')); ?>">New Project</a>
        <hr>
    
        <table class="table">
            <thead>
                <tr>
                    <th>Project Name</th>
                    <th>Start Date</th>
                    <th>Location</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->projects as $project): ?>
                <tr>
                    <td><?php echo $project->getProjectName(); ?></td>
                    <td><?php echo $project->getStartDate()->format('d/m/Y'); ?></td>
                    <td><?php echo $project->getLocationOfWorks(); ?></td>
                    <td style="width: 1%;" nowrap>
                        <a class="btn btn-sm btn-warning" href="<?php echo $this->url('application/default', array(
                            'controller' => 'project',
                            'action'     => 'enter_detail',
                            'id'         => $project->getProjectId())) ?>">Edit</a>
                        <a class="btn btn-sm btn-danger" href="<?php echo $this->url('application/default', array(
                            'controller' => 'project',
                            'action'     => 'delete',
                            'id'         => $project->getProjectId())) ?>">Delete</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </body>
        </table>
    </div>
</div>
