<h1>Risk Assessment</h1>
<hr>

<a class="btn btn-sm btn-primary" href="<?php echo $this->url('application/default', array(
            'controller' => 'project',
            'action'     => 'enter_detail',
            'id'         => $this->id));?>">Previous</a>
<a class="btn btn-sm btn-primary" href="<?php echo $this->url('application/default', array(
            'controller' => 'project',
            'action'     => 'method_statement',
            'id'         => $this->id));?>">Next</a>