<style type="text/css">
    
    h1, h2, h3, h4 {
        font-weight: bold;
        font-family: 'Helvetica'
    }
    h1 {font-size: 28pt;}
    h2 {font-size: 14pt;}
    h3 {font-size: 11pt;}
    
    p, table {
        font-size: 11pt;
        font-family: 'Helvetica'
    }
    
    td {
        vertical-align: top;
        padding-bottom: 10px;
    }
    
    .center {
        text-align: center;
    }
    
</style>