<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Gallium') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-1.11.3.min.js'))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('application') ?>">Gallium</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'project')) ?>"><?php echo $this->translate('Projects') ?></a></li>
                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'activity')) ?>"><?php echo $this->translate('Risks') ?></a></li>
                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'method')) ?>"><?php echo $this->translate('Methods') ?></a></li>
                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'substance')) ?>"><?php echo $this->translate('Substances') ?></a></li>
                        <li><a href="<?php echo $this->url('application/default', array('controller' => 'ppe')) ?>"><?php echo $this->translate('PPEs') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p><small>Gallium Application created 2015 - by Steve Rayner
                        (Williams Refrigeration)</small></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
