
<div class="row">
    <div class="col-md-12">
        <h1>Add New Method Statement</h1>
        <hr>
    
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('application/default', array('controller' => 'method', 'action' => 'add', 'id' => $this->methodId)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
        ?>

        
    </div>
</div>