
<div class="row">

    <div class="col-md-12">
        <div class="jumbotron">
            <h1>Gallium</h1>
            <p>Risk Assessments, Method Statements & COSHH Management.</p>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Projects</h3>
            </div>
            <div class="panel-body">
                <p>Create projects to add risk assessments and  method statements to. View and update existing projects.</p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore Projects') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Method Statements</h3>
            </div>
            <div class="panel-body">
                <p>Generate a method statement for a project by simply selecting the relevant activities. Either print
                    or email the method statement.</p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Create Method Statement') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">COSHH Sheets</h3>
            </div>
            <div class="panel-body">
                <p>Add relevant COSHH sheets to a project by selecting the chemicals in use.</p><br>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Add COSHH Sheets') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    

    
</div>
